# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wwallas- <wwallas-@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/08 11:29:49 by wwallas-          #+#    #+#              #
#    Updated: 2022/12/08 13:52:57 by wwallas-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME	=	megaphone

CC		=	c++
CFLAGS	=	-Wall -Wextra -Werror  -std=c++98

SOURCES	=	megaphone.cpp

all:

$(NAME):
	gcc megaphone.cpp
